import { db } from "@/db";
import { transactions, recurringTransactions } from "@/db/schema";
import { and, eq, gte, lt, isNull } from "drizzle-orm";
import { projectRecurringOccurrences } from "@/lib/format/date";

export type ForecastHorizonDays = 30 | 60 | 90;
export type ForecastConfidence = "low" | "medium" | "high";

export interface CashflowForecastResult {
  horizonDays: ForecastHorizonDays;
  projectedIncome: number;
  projectedExpense: number;
  projectedNetCashflow: number;
  recurringIncome: number;
  recurringExpense: number;
  estimatedVariableIncome: number;
  estimatedVariableExpense: number;
  confidence: ForecastConfidence;
  /** Number of days of non-recurring transaction history actually used as the baseline (<= 90) */
  historyDaysUsed: number;
  insufficientData: boolean;
  /** Vietnamese disclaimer to surface in the UI, as required by product spec */
  disclaimer: string;
}

const DISCLAIMER = "Dự báo được ước tính từ dữ liệu lịch sử và giao dịch định kỳ.";
const TRAILING_HISTORY_DAYS = 90;

/**
 * Deterministic cashflow forecast for the next 30/60/90 days.
 *
 * Method:
 * 1. Known future cashflows: project recurring transactions (income/expense)
 *    forward across the horizon using their frequency + start/end rules.
 * 2. Variable spending baseline: average daily income/expense from the
 *    trailing 90 days of COMPLETED, non-transfer transactions that are NOT
 *    linked to a recurring transaction (recurringTransactionId IS NULL) —
 *    this avoids double-counting amounts already captured by step 1.
 * 3. projected = recurring (exact) + variable baseline * horizonDays.
 *
 * This is a purely deterministic statistical projection, not a guarantee.
 */
export class ForecastService {
  /**
   * @param asOf Deterministic clock for this forecast computation. Defaults to `new Date()`
   *   for normal callers. MUST be threaded through explicitly (not re-read via `new Date()`
   *   anywhere else in this method) so that a single call — or the 30/60/90 fan-out in
   *   `getForecastSummary` — always reasons about one consistent "now", and so tests can pass
   *   a fixed clock instead of racing against wall-clock time between test setup and the
   *   service's own `new Date()` call.
   */
  static async getForecast(
    userId: string,
    horizonDays: ForecastHorizonDays,
    asOf: Date = new Date()
  ): Promise<CashflowForecastResult> {
    const now = asOf;
    const horizonEnd = new Date(now.getTime() + horizonDays * 24 * 60 * 60 * 1000);
    const historyStart = new Date(now.getTime() - TRAILING_HISTORY_DAYS * 24 * 60 * 60 * 1000);

    // 1. Known future cashflows from active recurring transactions
    const recurring = await db
      .select()
      .from(recurringTransactions)
      .where(and(eq(recurringTransactions.userId, userId), eq(recurringTransactions.isActive, true)));

    let recurringIncome = 0;
    let recurringExpense = 0;
    for (const rt of recurring) {
      // QUAN TRỌNG: dùng rt.nextDueDate (không phải `now`) làm mốc dưới của cửa sổ chiếu.
      // Nếu nextDueDate đã tới hạn hoặc quá hạn (<= now, vì cron xử lý theo lịch riêng,
      // không đồng bộ với thời điểm gọi forecast) mà vẫn lọc theo `now`, occurrence gần
      // nhất — occurrence chắc chắn nhất — sẽ bị loại khỏi dự báo, khiến recurringIncome/
      // recurringExpense bị tính thiếu hoặc bằng 0 một cách sai lệch.
      const occurrences = projectRecurringOccurrences(
        {
          id: rt.id,
          type: rt.type,
          amount: rt.amount,
          frequency: rt.frequency,
          startDate: rt.startDate,
          endDate: rt.endDate,
          nextDueDate: rt.nextDueDate,
          note: rt.note,
        },
        rt.nextDueDate,
        horizonEnd
      );
      const total = occurrences.length * rt.amount;
      if (rt.type === "income") recurringIncome += total;
      else recurringExpense += total;
    }

    // 2. Historical baseline: trailing 90 days, excluding transfers and
    // excluding transactions already generated by a recurring rule, so we
    // don't double-count what step 1 already projects exactly.
    const historicalTxs = await db
      .select({
        type: transactions.type,
        amount: transactions.amount,
        transactionDate: transactions.transactionDate,
      })
      .from(transactions)
      .where(
        and(
          eq(transactions.userId, userId),
          eq(transactions.status, "completed"),
          gte(transactions.transactionDate, historyStart),
          lt(transactions.transactionDate, now),
          isNull(transactions.recurringTransactionId)
        )
      );

    let historicalIncome = 0;
    let historicalExpense = 0;
    let earliestTxDate: Date | null = null;
    for (const tx of historicalTxs) {
      if (tx.type === "income") historicalIncome += tx.amount;
      else if (tx.type === "expense") historicalExpense += tx.amount;
      // transfers are intentionally excluded entirely (not income/expense)
      if (!earliestTxDate || tx.transactionDate < earliestTxDate) earliestTxDate = tx.transactionDate;
    }

    const historyDaysUsed = earliestTxDate
      ? Math.min(TRAILING_HISTORY_DAYS, Math.max(1, Math.ceil((now.getTime() - earliestTxDate.getTime()) / (24 * 60 * 60 * 1000))))
      : 0;

    const dailyIncomeRate = historyDaysUsed > 0 ? historicalIncome / historyDaysUsed : 0;
    const dailyExpenseRate = historyDaysUsed > 0 ? historicalExpense / historyDaysUsed : 0;

    const estimatedVariableIncome = Math.round(dailyIncomeRate * horizonDays);
    const estimatedVariableExpense = Math.round(dailyExpenseRate * horizonDays);

    const projectedIncome = recurringIncome + estimatedVariableIncome;
    const projectedExpense = recurringExpense + estimatedVariableExpense;
    const projectedNetCashflow = projectedIncome - projectedExpense;

    const insufficientData = historyDaysUsed === 0 && recurring.length === 0;

    let confidence: ForecastConfidence;
    if (insufficientData) {
      confidence = "low";
    } else if (historyDaysUsed >= 60 && recurring.length > 0) {
      confidence = "high";
    } else if (historyDaysUsed >= 20 || recurring.length > 0) {
      confidence = "medium";
    } else {
      confidence = "low";
    }

    return {
      horizonDays,
      projectedIncome,
      projectedExpense,
      projectedNetCashflow,
      recurringIncome,
      recurringExpense,
      estimatedVariableIncome,
      estimatedVariableExpense,
      confidence,
      historyDaysUsed,
      insufficientData,
      disclaimer: DISCLAIMER,
    };
  }

  static async getForecastSummary(
    userId: string,
    asOf: Date = new Date()
  ): Promise<Record<ForecastHorizonDays, CashflowForecastResult>> {
    // Capture ONE clock and pass it to all three horizons, so 30/60/90 are computed
    // against the exact same "now" instead of three independently-read clocks.
    const [d30, d60, d90] = await Promise.all([
      ForecastService.getForecast(userId, 30, asOf),
      ForecastService.getForecast(userId, 60, asOf),
      ForecastService.getForecast(userId, 90, asOf),
    ]);
    return { 30: d30, 60: d60, 90: d90 };
  }
}

export const forecastService = ForecastService;
