/**
 * Integration test for ForecastService — verifies recurring projection,
 * transfer exclusion, non-double-counting of recurring-generated
 * transactions, and confidence levels.
 *
 * Uses a dedicated, freshly created test user + isolated financial data and
 * cleans up everything in `finally`, per DATABASE_RULES.md 6.5.
 */
import { db } from "../src/db";
import { users, financialAccounts, transactions, recurringTransactions } from "../src/db/schema";
import { ForecastService } from "../src/server/services/forecast";
import * as assert from "assert";
import { eq } from "drizzle-orm";

async function run() {
  console.log("Setting up Cashflow Forecast test...");

  const [testUser] = await db
    .insert(users)
    .values({
      id: crypto.randomUUID(),
      name: "Phase6 Forecast Test User",
      email: `phase6-forecast-${Date.now()}@example.test`,
    })
    .returning();

  try {
    const now = new Date();

    const [account] = await db
      .insert(financialAccounts)
      .values({
        id: crypto.randomUUID(),
        userId: testUser.id,
        name: "Test Account",
        type: "bank",
        balance: 5_000_000,
      })
      .returning();
    const [account2] = await db
      .insert(financialAccounts)
      .values({
        id: crypto.randomUUID(),
        userId: testUser.id,
        name: "Test Account 2",
        type: "bank",
        balance: 0,
      })
      .returning();

    // 1. No data at all -> insufficient data, low confidence.
    // Truyền chung `now` cho MỌI lần gọi getForecast trong test này, để tránh
    // ForecastService tự đọc `new Date()` ở một thời điểm khác (dù chỉ vài ms sau) —
    // đó chính là nguyên nhân gốc khiến occurrence tại nextDueDate === now bị coi là
    // "trước" forecast start và bị loại khỏi projection.
    const emptyForecast = await ForecastService.getForecast(testUser.id, 30, now);
    assert.strictEqual(emptyForecast.insufficientData, true, "No history + no recurring must be insufficientData");
    assert.strictEqual(emptyForecast.confidence, "low");
    assert.strictEqual(emptyForecast.projectedIncome, 0);
    assert.strictEqual(emptyForecast.projectedExpense, 0);

    // 2. A monthly recurring salary of 10,000,000 -> should project ~1 occurrence in 30 days.
    const [recurring] = await db
      .insert(recurringTransactions)
      .values({
        id: crypto.randomUUID(),
        userId: testUser.id,
        accountId: account.id,
        amount: 10_000_000,
        type: "income",
        frequency: "monthly",
        startDate: now,
        nextDueDate: now,
        isActive: true,
      })
      .returning();

    const withRecurring = await ForecastService.getForecast(testUser.id, 30, now);
    assert.ok(withRecurring.recurringIncome >= 10_000_000, "Recurring income must be projected exactly, not estimated");

    // 3. A non-recurring historical expense (last 10 days) must feed the variable baseline,
    // while a TRANSFER in the same window must be excluded entirely from both income/expense.
    const tenDaysAgo = new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000);
    await db.insert(transactions).values([
      {
        id: crypto.randomUUID(),
        userId: testUser.id,
        accountId: account.id,
        type: "expense",
        amount: 1_000_000,
        transactionDate: tenDaysAgo,
        status: "completed",
      },
      {
        id: crypto.randomUUID(),
        userId: testUser.id,
        accountId: account.id,
        toAccountId: account2.id,
        type: "transfer",
        amount: 2_000_000,
        transactionDate: tenDaysAgo,
        status: "completed",
      },
      // A transaction that WAS generated by the recurring rule above must NOT be
      // double counted into the variable baseline.
      {
        id: crypto.randomUUID(),
        userId: testUser.id,
        accountId: account.id,
        type: "income",
        amount: 10_000_000,
        transactionDate: tenDaysAgo,
        status: "completed",
        recurringTransactionId: recurring.id,
        recurringOccurrenceDate: tenDaysAgo,
      },
    ]);

    const withHistory = await ForecastService.getForecast(testUser.id, 30, now);
    assert.ok(withHistory.estimatedVariableExpense > 0, "Variable expense baseline must reflect the non-recurring expense");
    assert.ok(
      withHistory.estimatedVariableIncome < 10_000_000,
      "The recurring-linked income transaction must be excluded from the variable baseline (no double counting)"
    );
    assert.strictEqual(withHistory.confidence !== "low", true, "Should no longer be low confidence with recurring + history");

    // 4. Horizons scale roughly proportionally for the variable component.
    const forecast90 = await ForecastService.getForecast(testUser.id, 90, now);
    assert.ok(
      forecast90.estimatedVariableExpense >= withHistory.estimatedVariableExpense,
      "Longer horizon must project at least as much variable expense"
    );

    console.log("✓ Insufficient-data case returns low confidence, zero projections");
    console.log("✓ Recurring transactions projected exactly");
    console.log("✓ Transfers excluded from forecast entirely");
    console.log("✓ Recurring-linked transactions excluded from variable baseline (no double counting)");
    console.log("✓ 30/60/90 horizons scale consistently");
    console.log("PASS");
  } finally {
    await db.delete(recurringTransactions).where(eq(recurringTransactions.userId, testUser.id));
    await db.delete(transactions).where(eq(transactions.userId, testUser.id));
    await db.delete(financialAccounts).where(eq(financialAccounts.userId, testUser.id));
    await db.delete(users).where(eq(users.id, testUser.id));
    console.log("Cleanup complete.");
  }
}

run()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("FAIL", err);
    process.exit(1);
  });
